name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install pyntcloud
      run: |
        pip install ".[all]"
    - name: Test and coverage with pytest
      run: |
        pip install pytest
        pip install pytest-cov

        pytest --cov=pyntcloud --cov-report=xml --cov-append tests/unit
        pytest --cov=pyntcloud --cov-report=xml --cov-append tests/integration

    - name: Upload coverage to Codecov
      if: matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.11'
      run: bash <(curl -s https://codecov.io/bash) -t $TOKEN -B $REF
      env:
        TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        REF: "${{ github.ref }}"
